# Farmwelt Plugin by Dervonnebe

language: "de" # Available languages: de, en
farmwelt-world: "farmwelt" # World name for the farmworld
nether-farmwelt-world: "farmwelt_nether" # World name for the nether farmworld
end-farmwelt-world: "farmwelt_end" # World name for the end farmworld

random-teleport-distance: 1000 # Fallback

farmwelt-settings:
  use-random-teleport: true
  teleport-distance: 2000
  generator: "" # Custom generator name, e.g., "TerraformGenerator"
  world-border:
    size: 5000 # Size of the world border (diameter)
  chunky:
    enabled: false # Enable Chunky pre-generation
    radius: 2500 # Radius for Chunky pre-generation (should be half of world-border size)

nether-world-settings:
  use-random-teleport: true
  teleport-distance: 300
  generator: ""
  world-border:
    size: 5000
  chunky:
    enabled: false
    radius: 2500

end-world-settings:
  use-random-teleport: true
  teleport-distance: 1500
  generator: ""
  world-border:
    size: 5000
  chunky:
    enabled: false
    radius: 2500

use-bstats: true # Set to false to disable bStats metrics collection

default-permission: "farmwelt.use" # Permission for /farmwelt
admin-permission: "farmwelt.admin" # Permission for /farmwelt reset

# Rotating seeds
rotating-seeds:
  enabled: false
  normal-world-seeds:
    - 1234567890
  nether-world-seeds:
    - 1122334455
    - 5544332211
  end-world-seeds:
    - 6677889900
    - 0099887766

reset-schedule:
  timezone: "Europe/Berlin" # Timezone for reset
  time: "03:00" # Uhrzeit für den Reset im Format HH:mm
  daily: true
  weekly: false
  monthly: false
  day-of-week: 1 # 1 (Monday) to 7 (Sunday)
  day-of-month: 1 # 1 to 31

# Menu configuration
menu:
  normal-world:
    material: "GRASS_BLOCK"
    name: "&aFarmwelt"
  nether-world:
    enabled: false
    material: "NETHERRACK"
    name: "&cNether Farmwelt"
  end-world:
    enabled: false
    material: "END_STONE"
    name: "&5End Farmwelt"

enable-back-command: true # Spieler können sich mit /farmwelt back zurück teleportieren